[package]
name = "ahqstore-sdk"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "3.1.2"

[features]
default = ["abi"]
# Exports C abi wrapper
abi = []
